### ISSUE TITLE
On Kodi 21 (Omega) live TV stops after appr. 20 sec.

### ISSUE THREAD

**Issue by dimkroon** [vonH/plugin.video.iplayerwww#369] opened 2024-01-01 20:18 UTC
@CaptainTK 
In case you are not aware of recent discussions on the Kodi forum, this is just to inform you of an issue playing live content in Kodi Omega. First mentioned in [this post](https://forum.kodi.tv/showthread.php?tid=353349&pid=3169647#pid3169647)

It seem very much to be an issue with Inputstream Adaptive and I'm pretty sure there's nothing that can be done by iPlayer WWW. 
I've tried to check myself, but so far have not managed to build Omega on my system.
It could well be a duplicate of https://github.com/xbmc/inputstream.adaptive/issues/1432, but  think IA people need to be informed anyway to get a grasp of how big that problem is. I could take that up if you want, but I need a working Omega first.

**Comment by CaptainTK** [comment] 2024-01-02 17:24
Saw that conversation some time ago. I prefer to be a late adopter and let the devs of IA sort out things on their own before I report any bugs.

So if you want to invest time here knock yourself out. My recommendation to everyone on the forum would be to stick to 20 for the time being.

**Comment by DaveCheltenham** [comment] 2024-03-13 13:28
The problem is still there on RC1. The same on BBC Sound app.

**Comment by CaptainTK** [comment] 2024-05-26 06:06
Reported fixed in Inputstream Adaptive 21.4.4.

**Closed as completed by CaptainTK** 2024-05-26 06:06 UTC
