### ISSUE TITLE
Core dump on Kodi 17.3/Linux

### ISSUE THREAD

**Issue by bitterjug** [vonH/plugin.video.iplayerwww#185] opened 2017-05-28 10:30 UTC
I installed v 3.0.7 of the plugin just now on my mythbuntu htpc (Kodi 17.3).
Can get a list of categories and programmes but at some point Kodi crashes (segmentation fault, core dumped) . I get some number of the following error before the core dump:
```
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter. Returning 0.
```
Have tried adding my bbc credentials to the pugin settings but the same happens.

**Comment by CaptainTK** [comment] 2017-05-29 18:30
Thanks for reporting this problem. I have never seen anything like this, but then I am still on 17.1.

Is there anything you can do to trigger the problem or does it occur randomly?

For your understanding: An add-on is only active while you do something. For example, if you click on Categories, the Categories listing is generated until it is ready for display. From this point of time onwards, it is only Kodi itself that is active, not the add-on. Only when you select a programme by clicking on it, the add-on code is executed again. I doubt that the add-on can actually crash Kodi. It seems much more likely to me that this is an issue in Kodi itself.

**Comment by CaptainTK** [comment] 2017-06-05 12:39
Do you have any additional information on this, @bitterjug ? Otherwise I would close here.

**Comment by bitterjug** [comment] 2017-06-06 07:26
Sorry. Havent had chance to revisit as traveling for work. Ill take a look
next week.

**Comment by CaptainTK** [comment] 2020-12-22 15:38
Could not reproduce. Closing.

**Closed by CaptainTK** 2020-12-22 15:38 UTC
