### ISSUE TITLE
Addon not working

### ISSUE THREAD

**Issue by thetravellor** [vonH/plugin.video.iplayerwww#329] opened 2020-09-02 16:06 UTC
Kodi 18  on Raspberry Pi 4, Raspbian Buster 10

I am running nordvpn via openvpn and have verified I can connect to and play BBC in the Pi's chromium browser.

However when I run the iPlayer addon from within kodi I simply get a blue icon with a back arrow.

I have attached the kodi debug log.

[kodi.log](https://github.com/vonH/plugin.video.iplayerwww/files/5163438/kodi.log)

**Comment by CaptainTK** [comment] 2020-09-02 16:28
Nothing useful in the log. If you only get a spinning circle, not even the add-on's main menu, then the issue is in between Kodi and the add-on itself. Are you using a Kodi 18 build based on Python 3? I'd so, this is not supported.

In any case, the usage of VPNs is banned, so I am closing this issue, even thought is not connected to VPN usage.

**Closed by CaptainTK** 2020-09-02 16:28 UTC

**Comment by thetravellor** [comment] 2020-09-04 08:26
Hello,

 

I am using the default Kodi 18 and python as provided by the standard Rasberry Pi 4 / Raspbian 10 repositories. How on earth can you suggest that it is not supported.

 

This is the log entry

 

020-09-03 01:58:50.613 T:2972466272   DEBUG: ------ Window Init (DialogBusy.xml) ------

2020-09-03 01:58:50.672 T:2123747536   DEBUG: -->Python Interpreter Initialized<--

2020-09-03 01:58:50.672 T:2123747536   DEBUG: CPythonInvoker(3, /home/pi/.kodi/addons/plugin.video.iplayerwww/default.py): the source file to load is "/home/pi/.kodi/addons/plugin.video.iplayerwww/default.py"

2020-09-03 01:58:50.673 T:2123747536   DEBUG: CPythonInvoker(3, /home/pi/.kodi/addons/plugin.video.iplayerwww/default.py): setting the Python path to /home/pi/.kodi/addons/plugin.video.iplayerwww:/home/pi/.kodi/addons/script.module.certifi/lib:/home/pi/.kodi/addons/script.module.chardet/lib:/home/pi/.kodi/addons/script.module.idna/lib:/home/pi/.kodi/addons/script.module.requests/lib:/home/pi/.kodi/addons/script.module.urllib3/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/gtk-2.0

2020-09-03 01:58:50.673 T:2123747536   DEBUG: CPythonInvoker(3, /home/pi/.kodi/addons/plugin.video.iplayerwww/default.py): entering source directory /home/pi/.kodi/addons/plugin.video.iplayerwww

2020-09-03 01:58:50.673 T:2123747536   DEBUG: CPythonInvoker(3, /home/pi/.kodi/addons/plugin.video.iplayerwww/default.py): instantiating addon using automatically obtained id of "plugin.video.iplayerwww" dependent on version 2.25.0 of the xbmc.python api

2020-09-03 01:58:52.344 T:2123747536   DEBUG: CAddonSettings[plugin.video.iplayerwww]: loading setting definitions

2020-09-03 01:58:52.344 T:2123747536   DEBUG: CAddonSettings[plugin.video.iplayerwww]: trying to load setting definitions from old format...

2020-09-03 01:58:52.345 T:2123747536   DEBUG: CAddonSettings[plugin.video.iplayerwww]: loading setting values

2020-09-03 01:58:52.346 T:2123747536   DEBUG: CSettingsManager: requested setting (licence_warning_shown) was not found.

2020-09-03 01:58:52.346 T:2123747536   DEBUG: CAddonSettings[plugin.video.iplayerwww]: failed to find definition for setting licence_warning_shown. Creating a setting on-the-fly...

2020-09-03 01:58:52.346 T:2123747536   DEBUG: CSettingsManager: requested setting (kids_password) was not found.

2020-09-03 01:58:52.415 T:2123747536    INFO: CPythonInvoker(3, /home/pi/.kodi/addons/plugin.video.iplayerwww/default.py): script successfully run

2020-09-03 01:58:52.415 T:2123747536   DEBUG: onExecutionDone(3, /home/pi/.kodi/addons/plugin.video.iplayerwww/default.py)

2020-09-03 01:58:52.417 T:2352570576   DEBUG: Thread waiting 2352570576 terminating

 

Not resolving the issue because I am using a VPN is in use is a bit over the top, however VPNs “bannable”? We live in a democracy and they are not illegal. Its also nothing to do with the issue.

 

Fix it or ignore it, I am simply trying to help improve your app as it is currently borked.

 

Regards.

**Comment by CaptainTK** [comment] 2020-09-04 11:51
The add-on is not borked. It works fine on my Raspi using OepnELEC. It works fine on my Linux desktop. That is what I am trying to tell you. The issue you are experiencing is on your end, not the add-on.

It might be a broken installation of either Kodi or the add-on. It might be a Python 3 based build of Kodi, which is not compatible with the add-on.

It most certainly has got nothing to do with your VPN usage. Nevertheless, any issue is not supported once you use a VPN. This is like a broken warranty seal on a box. Despite that, I tried helping you, but you either don't want to listen, or don't understand. In any case, there is nothing more I can do here.
