### ISSUE TITLE
highlights fallback

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#206] opened 2017-08-19 11:29 UTC
How about having a fallback function that just tries to scrape the hrefs if it can't find any programs? That would be useful for changes we can't keep up with like the Highlights page. The episode name is in the url so it just needs a bit of capitalization to look ok. Just forget about images etc.
regex
`href=".*?/episode/.*?"`
eg
`href="http://www.bbc.co.uk/iplayer/episode/p055b0y4/ill-behaviour-series-1-episode-1"`
`Ill Behaviour Series 1 Episode 1`

**Comment by CaptainTK** [comment] 2017-08-19 16:10
The problem is: I don't even get hrefs for some of the experimental designs. It seems to be controlled by Cookies and is semi-random. One thing we need to do for sure is move to https for accessing the pages. http pages come up almost empty for me.

**Comment by primaeval** [comment] 2017-08-19 16:59
It's probably because they assume you'll log in there now to watch programs. They usually have your watch list and recommendations on there. Do you consistently get something if you start with https on the highlights page?

**Comment by CaptainTK** [comment] 2017-08-19 17:48
I get something with https, but still different new designs in the browser and in Kodi.

**Comment by primaeval** [comment] 2017-08-19 18:40
Even with the same user-agent value?

**Comment by CaptainTK** [comment] 2017-08-19 18:54
Almost the same user agent. Different OS...

**Comment by CaptainTK** [comment] 2017-10-03 11:05
Highlights seems stable again, I fixed it in 2.5.23 and 3.0.15. Actually, the new HTML is quite nice to parse, so I currently see no need for a fallback and will close this.

**Closed by CaptainTK** 2017-10-03 11:05 UTC
